### ISSUE TITLE
Allow to specify exit code for fatal errors

### ISSUE THREAD

**Issue by mabrarov** [powerman/dockerize#103]
It looks like the exit code for fatal errors (like timeout when waiting for something) is hard-coded and is 123. Refer to [main.go:26](https://github.com/powerman/dockerize/blob/master/main.go#L26).

In some cases users of Dockerize may need different exit code to avoid possible conflict with application exit code.

In some cases users of Dockerize may need different exit code when wait fails, e.g. if Dockerize is used in a Docker health check (without shell, because in some images - like Distroless - shell can be missing), then [exit code of health check](https://docs.docker.com/engine/reference/builder/#healthcheck) has to meet following requirements:

> The command’s exit status indicates the health status of the container. The possible values are:
> 
> * 0: success - the container is healthy and ready for use
> * 1: unhealthy - the container is not working correctly
> * 2: reserved - do not use this exit code

While it looks like even 123 exit code works with Docker (tested with [mabrarov/docker-compose-init-container](https://github.com/mabrarov/docker-compose-init-container) on CentOS 7 / Docker 1.12.x-1.13.x), it would be nice if users of Dockerize can follow requirements of Docker health check when using Dockerize with [exec array format of Dockerfile `HEALHTCHECK` instruction](https://github.com/GoogleContainerTools/distroless/issues/183#issuecomment-823181507).

Thank you for investment into enhancement of Dockerize!

**Comment by powerman** [comment]
Thing is, exit code 123 was chosen to minimize a chance to conflict with exit code of provided user's command (usually started by dockerize). Thus codes 0-1-2 are not really suitable here as they've very high chance to conflict.

If you're using dockerize without starting user command then you can do something like:
```sh
dockerize … || exit 1
# OR
dockerize …
code=$?
test $code -eq 123 && exit 1 || exit $code
```

**Comment by mabrarov** [comment]
> If you're using dockerize without starting user command then you can do something like

I cannot do this, because in my case I have no shell (and don't want to have it because of security reasons).

**Comment by powerman** [comment]
I see. But why do you use dockerize for health-check at first place? Why not `curl` etc.? (BTW, curl's exit codes also doesn't match docker's health-check requirements.)

To me it's unclear why dockerize is suitable for health-checks - probing ports is often now enough for good health-check, plus docker's HEALTHCHECK features duplicate dockerize ones (timeout, retries, etc.).

**Comment by mabrarov** [comment]
> Why not curl etc.? 

Because 

> BTW, curl's exit codes also doesn't match docker's health-check requirements.

Regarding 

> To me it's unclear why dockerize is suitable for health-checks

Why one uses curl / wget for Docker health check? Why couldn't we use Dockerize (which is a tool for containers) for the same, but meeting requirements of Docker health check? I mean it's meaningless to ask curl / wget to implement customizable exit codes for fatal errors just to meet requirements of Docker health check, because those tools are not designed specifically for containerization (comparing to Dockerize).

> probing ports is often not enough for good health-check

Dockerize can check HTTP and HTTPS endpoints just like curl / wget, can't it?

**Comment by powerman** [comment]
Well, while dockerize is designed "for docker" it doesn't means it is designed for everything docker-related. If you'll read first sentence in README you'll see it's designed for "running applications", not for health-check or anything else.

> Dockerize can check HTTP and HTTPS endpoints just like curl / wget, can't it?

Not really. Dockerize isn't as flexible as curl/wget.

But… okay. If we rephrase this issue to "… to avoid possible conflict with application exit code" then such a feature will fit dockerize purpose just fine and as a side effect will also solve your issue with (mis)using dockerize for health-checks. :smile:

**Comment by mabrarov** [comment]
> "… to avoid possible conflict with application exit code" then such a feature will fit dockerize purpose just fine and as a side effect will also solve your issue

Yeah, I was thinking about the same when got your first response about the reason of 123 exit code.

I understand that Dockerize cannot be a "swiss army knife", but Dockerize is sooo helpful, that it's hard to not ask for new features :)

**Comment by powerman** [comment]
Released in 0.14.0. Released binary/image will be available in a few minutes.

**Comment by mabrarov** [comment]
Thank you. The `-exit-code` parameter works as expected. I successfully tested it with [mabrarov/docker-compose-init-container](https://github.com/mabrarov/docker-compose-init-container). 

The only missing thing is documentation - `-exit-code` flag is not documented in [README.md](https://github.com/powerman/dockerize/blob/master/README.md).

**Comment by powerman** [comment]
I know. I doubt README documents every possible flag. And it's documented in `-h` output.
