### ISSUE TITLE
feat: metrics support

### ISSUE THREAD

**Issue by lukasmrtvy** [powerman/dockerize#151]
would be great to support metrics in openmetrics format:

metrics:
- `dockerize_wait_status{container_id="<id>", wait_http_web1_80="ready", wait_http_web2_8080="retrying", wait_http_web3_8080="failed" X`
- `dockerize_hotreloaded{container_id="<id>"} 1`

https://github.com/powerman/dockerize/issues/150

thanks

**Comment by powerman** [comment]
Dockerize won't usually keep running, so I can't see how metrics can be useful.
Usually you already have all metrics you need: either from docker itself (because container fails to start, e.g. if dockerize fails to wait for something) or from your app (started by dockerize after successful wait).
