### ISSUE TITLE
Release 0.16.2 doesn't have assets

### ISSUE THREAD

**Issue by chriiiish** [powerman/dockerize#233]
Previous versions of dockerize have different assets for different platforms:
![image](https://user-images.githubusercontent.com/3358790/180907975-ae919def-103c-4e67-b264-87c529d19cc9.png)

But the latest one just has the source code:
![image](https://user-images.githubusercontent.com/3358790/180908031-ab86bbf5-4631-4be1-b622-c5f997ee5551.png)

This causes the installation to fail when using `latest`:
![image](https://user-images.githubusercontent.com/3358790/180908119-4b0b9f9f-504f-4e13-bc6b-30119c3b933b.png)
![image](https://user-images.githubusercontent.com/3358790/180908237-8eeb1465-29b8-4705-9ec3-8cc7617d0376.png)

The dockerize executable is 0 bytes because the outer curl command fails. The outer curl command fails because because the inner curl/grep command cannot find the platform in the assets and so there is no URL returned, so curl throws an error saying you need to specify a url. This is from the docs:

```sh
curl -sfL $(curl -s https://api.github.com/repos/powerman/dockerize/releases/latest | grep -i /dockerize-$(uname -s)-$(uname -m)\" | cut -d\" -f4) | install /dev/stdin /usr/local/bin/dockerize
```

The assets just need to be added to the latest release

**Comment by chriiiish** [comment]
The end result of this is that dockerize fails with the following error:
```
exec /usr/local/bin/dockerize: exec format error
```
because the executable is 0 bytes.

**Comment by powerman** [comment]
Oops. I've updated GitHub Releaser tool and looks like this breaks something.

Thanks for the report, I'll take a look and fix it.

**Comment by powerman** [comment]
Fixed.

**Comment by chriiiish** [comment]
Thanks @powerman 🎉
