### ISSUE TITLE
Honoring PROXY settings

### ISSUE THREAD

**Issue by iaean** [powerman/dockerize#252]
Is it possible to let the http.Client honor HTTP_PROXY, HTTPS_PROXY and NO_PROXY from environment?

E.g. here https://github.com/powerman/dockerize/blob/c9d55019deed3e91858951e23c14a002be8439de/wait.go#L128

AFAIK its just add `Proxy: http.ProxyFromEnvironment` to the transport config. But I'm not really familiar with Go.

Thx for your investigation.

**Comment by powerman** [comment]
Sounds like a good idea!

**Comment by powerman** [comment]
Released in 0.17.0.
