### ISSUE TITLE
Templating: Working with optional environment variables in `-template-strict mode`

### ISSUE THREAD

**Issue by fknittel** [powerman/dockerize#37]
We're attempting to use dockerize in `-template-strict`-mode to fail early when there is a mismatch between the configuration templates and the docker environment definition.

But now we're struggling with the use of optional environment variables: `{{ if .Env.OPTIONAL_ENV }}` errors out as soon as OPTIONAL_ENV is undefined (as expected).
We tried `{{ if hasKey .Env "OPTIONAL_ENV " }}`, but that doesn't appear to work (`at <.Env>: wrong type for value; expected map[string]interface {}; got map[string]string`) as sprig's hasKey appears to only work on dicts and not on maps.

Our work-around is to drop `-template-strict` again, but we'd really like to be strict by default and clearly mark the places where we accept undefined variables.

Are we doing something wrong (quite new to go & text/template)? Or is this simply something that is missing from the templating language?

**Comment by powerman** [comment]
Sorry for delay.

Thing is, strict mode is not suitable for optional variables, because it's goal is exactly opposite: prevent missing variable.

So, you have to either define ALL used variables (i.e. instead of absent env variable use existing variable with empty value) or give up on strict.
