### ISSUE TITLE
sha256 and asc in releases

### ISSUE THREAD

**Issue by micheelengronne** [powerman/dockerize#41]
Can you provide a sha256 file and an asc file for each binary in the releases section ?

It will give the possibility to enforce stronger download checks.

Thanks.

**Comment by powerman** [comment]
Probably, but how .asc file downloaded from GitHub releases page will make anything stronger if binary is downloaded from same GitHub releases page? I mean, if someone manage to replace binary, he'll replace .asc in same way…

**Comment by micheelengronne** [comment]
Yes and no. As asc contains an information about your gpg key and a hacker canno't fake your key. If someone alters the binary and the asc, the asc can only be signed by the hackers key, not yours.

When checking the asc, we check that it is your key that signed it and if it is not the case an error is reported.

**Comment by powerman** [comment]
Ah, you mean real signature (I thought you're talking about SHA checksum). Then I'm not sure I can do this - release process is automated and happens on CI, and I don't like to give CI my PGP private key.

**Comment by micheelengronne** [comment]
I talked about both to be more agnostic. If the release process is automated you can create a GPG key for the release bot and use it to sign the asc. To be more effective, you can then sign the GPG key of the bot with yours. That way, you don't give your key to the CI bot but you still can easily revoke its.

**Comment by powerman** [comment]
Sounds good to me. Will do when I'll have spare time. Thanks for the idea! :smile:

**Comment by powerman** [comment]
Done.

**Comment by powerman** [comment]
I should say gnupg is overly complicated. I won't mention amount of unobvious command I had to run just to create signing key… let's just see how users will be able to verify these signatures:

```bash
$ gpg --verify dockerize-linux-x86_64.asc dockerize-linux-x86_64
gpg: Signature made Tue May 19 07:53:34 2020 EEST
gpg:                using RSA key C7A98682819C34F047DF061822E220B62A14D58D
gpg: Can´t check signature: No public key

### Let's try to get the key…
$ gpg --recv-keys C7A98682819C34F047DF061822E220B62A14D58D
gpg: keyserver receive failed: General error

### Oops. Okay, let's pretend it's advanced gnupg user and try another server (I've uploaded to all of them).
$ gpg --keyserver hkp://pool.sks-keyservers.net --recv-keys C7A98682819C34F047DF061822E220B62A14D58D
gpg: keyserver receive failed: No data
$ gpg --keyserver hkp://keys.gnupg.net --recv-keys C7A98682819C34F047DF061822E220B62A14D58D
gpg: key D9994ED71A6E1994: public key "Alex Efros (sign key for CI) <powerman@powerman.name>" imported
gpg: Total number processed: 1
gpg:               imported: 1

### Cool! So, now we can verify?!
$ gpg --verify dockerize-linux-x86_64.asc dockerize-linux-x86_64
gpg: Signature made Tue May 19 07:53:34 2020 EEST
gpg:                using RSA key C7A98682819C34F047DF061822E220B62A14D58D
gpg: Good signature from "Alex Efros (sign key for CI) <powerman@powerman.name>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 37CE D4EE 1F89 840B AAA5  D1F5 D999 4ED7 1A6E 1994
     Subkey fingerprint: C7A9 8682 819C 34F0 47DF  0618 22E2 20B6 2A14 D58D

### So, let's try to check signature chain, to make sure it points to my main key:
$ gpg --list-sigs C7A98682819C34F047DF061822E220B62A14D58D
pub   rsa4096 2020-05-19 [SC]
      37CED4EE1F89840BAAA5D1F5D9994ED71A6E1994
uid           [ unknown] Alex Efros (sign key for CI) <powerman@powerman.name>
sig 3        D9994ED71A6E1994 2020-05-19  Alex Efros (sign key for CI) <powerman@powerman.name>
sub   rsa4096 2020-05-19 [S] [expires: 2021-05-19]
sig          D9994ED71A6E1994 2020-05-19  Alex Efros (sign key for CI) <powerman@powerman.name>

### Oops, looks like key is just self-signed. How is that? Let's see how it looks like in my main keyring:
$ gpg --list-sigs C7A98682819C34F047DF061822E220B62A14D58D
pub   rsa4096/0xD9994ED71A6E1994 2020-05-19 [SC]
      37CED4EE1F89840BAAA5D1F5D9994ED71A6E1994
uid                   [ultimate] Alex Efros (sign key for CI) <powerman@powerman.name>
sig 3        0xD9994ED71A6E1994 2020-05-19  Alex Efros (sign key for CI) <powerman@powerman.name>
sig          0x07743D4953C54FB5 2020-05-19  Alex Efros <powerman@powerman.name>
sub   rsa4096/0x22E220B62A14D58D 2020-05-19 [S] [expires: 2021-05-19]
sig          0xD9994ED71A6E1994 2020-05-19  Alex Efros (sign key for CI) <powerman@powerman.name>
```

It turns out some keyservers doesn't support third-party signatures (i.e. no Web of Trust support) and strip extra signatures. But I was unable to `--recv-keys` with signature of my main key from all keyservers I've tried (I've sent keys to 4, and 2 of them fail to recv later, while other 2 fail to keep extra signature).

This effectively means I have to somehow provide file with my public keys, because that's only way to actually check signatures. :disappointed:

**Comment by micheelengronne** [comment]
Awesome

**Comment by powerman** [comment]
A note for future myself: **how to change sign key expiration date** every year.
```
$ gpg --edit-key 37CED4EE1F89840BAAA5D1F5D9994ED71A6E1994
gpg> key 1
gpg> expire
1y
gpg> save
$ gpg --export-secret-subkeys --armor 37CED4EE1F89840BAAA5D1F5D9994ED71A6E1994 | perl -pE 's/\n/\\n/'
```
The set on CI env var `GPG_KEY` to the output of last command.

**Comment by powerman** [comment]
@micheelengronne I'm sorry, but looks like I'm giving up on this. Probably I'm just not smart enough to use GnuPG this way. I've just spent several hours trying to figure out why it now fail to import secret keys or why it fail to sign using imported keys… This feature just don't worth so much time. If you want it to work then please provide me with a cheat sheet how to manage subkeys.
