### ISSUE TITLE
checksum should reference the artifact

### ISSUE THREAD

**Issue by micheelengronne** [powerman/dockerize#43]
Currently the checksum file does contain the checksum but instead of the artifact filename it contains a `-`.

In order for the checksum file to work, it should reference the artifact filename. For instance, with gitea: https://github.com/go-gitea/gitea/releases/download/v1.12.0-rc1/gitea-1.12.0-rc1-darwin-10.6-386.sha256

**Comment by powerman** [comment]
Well, it was there few commits before, but I've removed it intentionally. Thing is, usually only one of binaries is downloaded, and then it's renamed to just `dockerize`. This means name hardcoded in .sha256 file won't match downloaded file name and thus check will fail. README contains example how to handle current files.

Feel free to reopen if you belive I'm wrong about this and have use case which require file names in .sha256 files and also have solution for use case mentioned above (single file download as per README install instructions).
