### ISSUE TITLE
Reopening issue #43

### ISSUE THREAD

**Issue by micheelengronne** [powerman/dockerize#44]
As stated in issue https://github.com/powerman/dockerize/issues/43

The current checksum does not work with automated systems.

Let's get ansible for instance. I use this module https://docs.ansible.com/ansible/latest/modules/get_url_module.html to download binaries.

In order for the [checksum parameter](https://docs.ansible.com/ansible/latest/modules/get_url_module.html#parameter-checksum) to work, the checksum file needs to have the complete binary name.

Generally, a binary is renamed after its checksum is verified as it would make no sense to execute any operation on a binary with a failing checksum (imagine that the binary is a malware that can benefit from a `cp` or `mv` fault).

**Comment by powerman** [comment]
Oookay. Done.
