### ISSUE TITLE
install: /dev/stdin: Inappropriate file type or format 

### ISSUE THREAD

**Issue by mmwebaze** [powerman/dockerize#48]
I am trying to install Dockerize macO Catalina Sbut I get the following error

stdin /usr/local/bin/dockerize
install: /dev/stdin: Inappropriate file type or format

**Comment by powerman** [comment]
Please provide complete output - which command(s) you run and their output.

**Comment by powerman** [comment]
Also, you can just download file manually from GitHub releases page, save it to /usr/local/bin and make it executable with `chmod +x /usr/local/bin/dockerize`.
