### ISSUE TITLE
Can you explain how to use untilStep function?

### ISSUE THREAD

**Issue by hniemann** [powerman/dockerize#9]
Can you explain how to use untilStep function?
I need a way to loop over a variable with multiple values

Like this...

TEST="val1 val2 val3"

{{ $i := loop .Env.TEST }}
foo = {{ $i }}
{{ end }}

Best regards
Heino

**Comment by powerman** [comment]
[Loop in original dockerize](https://github.com/jwilder/dockerize#loop) doesn't work this way. [untilStep](https://masterminds.github.io/sprig/integer_slice.html) is a drop in replacement for `loop`, but you need a [splitList](https://masterminds.github.io/sprig/string_slice.html):
```
{{ range $i := (splitList " " .Env.TEST) }}
foo = {{ $i }}
{{ end }}
```
